config/routes.rb
Rails.application.routes.draw do

  get '/change_guest' => 'guest_lists#edit'
  post '/change_guest' => 'guest_lists#update'
  delete '/change_guest' => 'guest_lists#destroy'

  get 'cost_list_newlyweds_summary' => 'cost_list_newlyweds_summary#index'
  get 'cost_list_events_summary' => 'cost_list_events_summary#index'
  get 'guest_list_events_summary' => 'guest_list_events_summary#index'
  get 'guest_list_confirmation_summary' => 'guest_list_confirmation_summary#index'
  get "/event_time_count_down" => 'event_time_count_downs#index'
  get "guest_list_events_newlyweds_summary" => "guest_list_events_newlyweds_summary#index"

  get "guest_list_newlywed_with_accompaning_people_summary" =>"guest_list_newlywed_with_accompaning_people_summary#index"
  get "guest_list_event_with_accompaning_people_summary" =>"guest_list_event_with_accompaning_people_summary#index"
  get "guest_list_companion" => "guest_list_companion#index"
  get "guest_list_newlywed_with_accompaning_people_summary" => "guest_list_newlywed_with_accompaning_people_summary#index"
  get "gest_lists" => "guest_lists#index"

  devise_for :superadmins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admin_user
  devise_for :guests, controllers: {
      registrations: 'guests/registrations',
    }

  resources :event_adresses
  resources :guest_lists
  resources :events
  resources :event_attendances
  resources :budgets
  resources :expenses
  resources :guest_adresses
  resources :posts

  get "/pages/:page" => "presentation_pages#show"
  root "presentation_pages#show", page: "welcome_page"

  # event attendance
  get "/update_event_attendance" => 'event_attendances#edit_event_attendance'
  post "/update_event_attendance" => 'event_attendances#update_event_attendance'

  # guest list
  get "/update_guest_list" => 'newlywed_guest_lists#edit_guest_list'
  post "/update_guest_list" => 'newlywed_guest_lists#update_guest_list'

  #budget
  get "/update_budgets" => 'budgets#edit_budgets'
  post "/update_budgets" => 'budgets#update_budgets'

  #accompaning person
  get "/update_accompaning_people" => 'companions#edit_accompaning_people'
  post "/update_accompaning_people" => 'companions#update_accompaning_people'

  #event guest list
  get "guest_list_events_summary" => 'guest_list_events_summary#index'

  #event attendance guest confirmations
  get "/update_ea_guest_confirmation" => 'ea_guest_confirmations#edit_ea_guest_confirmation'
  post "/update_ea_guest_confirmation" => 'ea_guest_confirmations#update_ea_guest_confirmation'

  get "/admin_update_ea_guest_confirmation" => 'ea_guest_confirmations#admin_edit_ea_guest_confirmation'
  post "/admin_update_ea_guest_confirmation" => 'ea_guest_confirmations#admin_update_ea_guest_confirmation'

  # lywed guest list
  get '/guest_list_newlywed_summary' => 'guest_list_newlywed_summary#index'

  # budget
  get "budget_max_how_much_money_lefts" => 'budget_max_how_much_money_lefts#index'
  get "budget_min_how_much_money_lefts" => 'budget_min_how_much_money_lefts#index'


end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :guest
  belongs_to :event
  belongs_to :admin_user

  def self.create_event_attendance_for_event_and_guest
    @guests = Guest.all
    @events = Event.all
    no_status = EventAttendanceStatus.find_by(eastatus:"no").id
    @guests.each do |guest|
      @events.each do |event|
        event_attendance = EventAttendance.new
        event_attendance.guest_id = guest.id
        event_attendance.event_id = event.id
        event_attendance.admin_user_id = 1
        event_attendance_status_id = no_status
        event_attendance.save
      end
    end
  end

end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController

  before_action :authenticate_admin_user!

  def create
    @event_attendance = current_admin_user.event_attendances.build(event_attendance_params)
    @event_attendance.save
  end

  def edit_event_attendance
    @guests = Guest.all
    @events = Event.all
    @event_attendance_statuses = EventAttendanceStatus.all
  end

  def index
    @events_attendance = EventAttendance.all
    @events = current_admin_user.events.all
    @guests = current_admin_user.guests.all
  end


  def update_event_attendance
    @guests = Guest.all
    @events = Event.all
    @event_attendance_statuses = EventAttendanceStatus.all
    @event_attendance = EventAttendance.find_by(id: params[:event_attendance][:event_attendance_id])
    @event_attendance.update_attributes(event_attendance_params)
  end

  def event_attendance_params
    params.require(:event_attendance).permit(:guest_id, :event_id, :status, :event_attendance_status_id)
  end
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/views/event_attendances/edit_event_attendance.html.erb
<h2> Update event attendance </h2>
<p>Assign a guest to a given event by selecting a status from the list</p>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Imię </th>
      <th scope="col">Nazwisko </th>
      <% @events.each do |event| %>
        <th scope="col"> <%= event.name %></th>
        <th scope ="col"> Save </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td> <%= guest.name %> </td>
        <td> <%= guest.surname %> </td>
        <% @events.each do |event| %>
          <% @event_attendance = EventAttendance.find_by(guest_id: guest.id, event_id: event.id)%>
            <%= form_for @event_attendance, url: {action: "update_event_attendance"}, method: :post do |f| %>
              <%= f.hidden_field :event_attendance_id, value: @event_attendance.id %>
              <td><%= f.collection_select :event_attendance_status_id, @event_attendance_statuses ,:id, :eastatus , include_blank: false %> </td>
              <td><%= f.submit "save" %> </td>
              <%= f.hidden_field :event_attendance_id, value: @event_attendance.id %>
            <% end %>
        <% end %>
      </tr>
    <%end %>
  </tbody>
</table>

app/views/event_attendances/update_event_attendance.html.erb
<table class="table">
  <thead>
        <tr>
          <th scope="col">Imię </th>
          <th scope="col">Nazwisko </th>
          <% @events.each do |event| %>
            <th scope="col"> <%=  event.name %>  </th>

            <th scope ="col"> Save </th>
          <% end %>
        </tr>
  </thead>
  <tbody>
      <% @guests.each do |guest| %>
      <tr>
        <td> <%= guest.name %> </td>
        <td> <%= guest.surname %> </td>
        <% @events.each do |event| %>

              <% @event_attendance = EventAttendance.find_by(guest_id: guest.id, event_id: event.id)%>

              <% @event_attendance_statuses = EventAttendanceStatus.all %>
              <%= form_for @event_attendance, url: edit_event_attendance_path(@event_attendance) do |f| %>
                <%= f.hidden_field :event_attendance_id, value: @event_attendance.id %>
                <td><%= f.collection_select :event_attendance_status_id, @event_attendance_statuses ,:id, :eastatus , include_blank: false %> </td>
                <td><%= f.submit "save" %> </td>
                <%= f.hidden_field :event_attendance_id, value: @event_attendance.id %>
              <% end %>


        <% end %>
          </tr>
      <%end %>
1

  </tbody>
</table>